DROP TABLE IF EXISTS CAMEL_MESSAGEPROCESSED CASCADE;
DROP TABLE IF EXISTS AUDITLOG CASCADE;


CREATE TABLE CAMEL_MESSAGEPROCESSED (
  PROCESSORNAME VARCHAR(255) NOT NULL,
  MESSAGEID VARCHAR(100) NOT NULL,
  CREATEDAT TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX CAMEL_MESSAGEPROCESSED_PK ON CAMEL_MESSAGEPROCESSED(PROCESSORNAME, MESSAGEID);  

CREATE TABLE AUDITLOG (
    BUSINESS_DATE DATE NOT NULL,
    APP_NAME VARCHAR2(30) NOT NULL,
    AUDIT_TYPE VARCHAR2(120) NOT NULL,
    SEVERITY VARCHAR2(32) NOT NULL,
    MESSAGE  VARCHAR2(255) NOT NULL,
    CREATE_TS DATE NOT NULL,
    UPDATE_TS DATE
);

CREATE TABLE  TRADE (  
	ORDER_ID VARCHAR2(30) NOT NULL,
	TRADE_ID NUMBER NOT NULL,
	BUSINESS_DAY DATE NOT NULL,
	SENDING_TIME TIMESTAMP NOT NULL,
	ISIN VARCHAR2(30) NOT NULL,
	TYPE VARCHAR2(5) NOT NULL,
	PRICE NUMBER NOT NULL
);

CREATE TABLE ISIN (
	NAME VARCHAR2(40) NOT NULL,
	ISIN VARCHAR2(12) PRIMARY KEY NOT NULL,
	COMMON_CODE VARCHAR2(10) NOT NULL,
	RATE NUMBER,
	CURRENCY VARCHAR2(5) NOT NULL,
	CLOSE_DATE DATE,
	NEXT_COUPON_DATE DATE,
	RECORD_DATE DATE,
	MARKET CHAR(1) NOT NULL, 
	INSTRUMENT VARCHAR2(12) NOT NULL,
	LAST_UPDATE DATE NOT NULL
);	


ALTER TABLE TRADE ADD CONSTRAINT IF NOT EXISTS TRADE_PK PRIMARY KEY(ORDER_ID);       

CREATE SEQUENCE IF NOT EXISTS FILE_SEQ;
CREATE SEQUENCE IF NOT EXISTS TRADE_SEQ;
CREATE SEQUENCE IF NOT EXISTS ORDER_SEQ;
